### PR TITLE
Removed the non-compliant apps from the appstore

### PR DESCRIPTION
**Pull request by tsthakur**
Based on EU meeting feedback, removed all the apps that were not compliant with the requirements. Fixed the minor issue of an app not showing the correct logo. Made a minor change to another app's name by dropping `app` from its name to make it more consistent with all other apps.

### CODE REVIEW

**Review by liotf — APPROVED** [review]

**Comment by PeterKraus** [comment]
Is there any chance such changes could be communicated to authors of the apps in the future? At least for the apps which have GH repositories. I don't mind at all that the app was removed, but I would at least like to know without having to be told via the grapevine...

**Comment by tsthakur** [comment]
Thank you for your query. All the authors were indeed contacted via emails and given ample time and multiple reminders to make their apps compliant with the regulations. I see that your email <Peter.Kraus@empa.ch> which was used to convey this information is not functional anymore, which might be the reason why you had to learn via grapevine about this change. If you can share your working email, I can forward you our intimation emails.

Besides this, as far as I know Francisco Ramirez has already opened PRs for both your apps to make them compliant. As soon as those are resolved and I will restore your apps to the appstore.

**Comment by PeterKraus** [comment]
Yeah, that's the joy of temporary positions: contracts end, emails vanish, people become unreachable through no fault of anyone. GitHub repos are probably more reliable. We'll get the PR's merged and then I'll make a PR here. It was just a suggestion for next time, anyway.

**Comment by tsthakur** [comment]
Yes, I understand how this can be frustrating. GitHub repositories may have been more reliable in this particular case, but when one needs to contact everyone 'formally' through proper channels, it can get trickier to do so without emails. But for next time, yes we can try doing both. Thank you for the suggestion.

**Pull request merged**
