### PR TITLE
Update apps.yaml

### PR DESCRIPTION
**Pull request by raulorteg**
Added a new app.

### CODE REVIEW

**Comment by raulorteg** [comment]
I changed the title since it seemed to make the automatic tests fail

**Review by liotf — APPROVED** [review]

**Review by csadorf — APPROVED** [review]

**Comment by csadorf** [comment]
@raulorteg Thanks! The logo has a white margin on the left. Feel free to submit another PR to fix that if you like.

**Comment by liotf** [comment]
The logo is a little off-centered.

**Comment by liotf** [comment]
@raulorteg Could you let us know what categories you would like your app to be in? Please select one or more valid categories specified in [categories.yaml](https://github.com/big-map/big-map-registry/blob/main/categories.yaml). We will insert your selection into apps.yaml on your behalf.

**Comment by raulorteg** [comment]
> @raulorteg We plan to make the "categories" field mandatory in the near future. Could you let us know what categories you would like your app to be in? Please select one or more valid categories specified in [categories.yaml](https://github.com/big-map/big-map-registry/blob/main/categories.yaml). We will insert your selection into apps.yaml on your behalf. Thanks for your understanding.

Hi, this is a generative model so maybe some tags that could be used is "deep learning", "machine learning", "inverse design", "generative model", "mlmd" or "machine learning for material discovery". Sorry I didnt add them myself, and thanks.

**Comment by csadorf** [comment]
@raulorteg Thanks a lot! Would you suggest to add those tags to the currently available tag list then? Which one of the already available tags would you want to apply? Finally, which WP does this app belong to?

**Comment by raulorteg** [comment]
> @raulorteg Thanks! The logo has a white margin on the left. Feel free to submit another PR to fix that if you like.

Thanks for letting me know, I just fixed it and I believe it should be updated automatically since the link now points to the changed file.

**Comment by raulorteg** [comment]
> @raulorteg Thanks a lot! Would you suggest to add those tags to the currently available tag list then? Which one of the already available tags would you want to apply? Finally, which WP does this app belong to?

Hi, yes I think it would be useful to add those tags to the list. From the ones currently available I believe none are a good fit, that is why I didnt add them to my pull request. From the ones I proposed I believe all apply but some might be redundant, I would use maybe "generative-model", "inverse-design", "mlmd". This app belongs to WP11. Thanks, for all and let me know if there is something else to do.

**Comment by liotf** [comment]
> > @raulorteg Thanks a lot! Would you suggest to add those tags to the currently available tag list then? Which one of the already available tags would you want to apply? Finally, which WP does this app belong to?
> 
> Hi, yes I think it would be useful to add those tags to the list. From the ones currently available I believe none are a good fit, that is why I didnt add them to my pull request. From the ones I proposed I believe all apply but some might be redundant, I would use maybe "generative-model", "inverse-design", "mlmd". This app belongs to WP11. Thanks, for all and let me know if there is something else to do.

Thanks a lot! Your app is now listed in the BIG-MAP App Store (<https://big-map.github.io/big-map-registry/index.html>).

**Comment by raulorteg** [comment]
> > > @raulorteg Thanks a lot! Would you suggest to add those tags to the currently available tag list then? Which one of the already available tags would you want to apply? Finally, which WP does this app belong to?
> > 
> > 
> > Hi, yes I think it would be useful to add those tags to the list. From the ones currently available I believe none are a good fit, that is why I didnt add them to my pull request. From the ones I proposed I believe all apply but some might be redundant, I would use maybe "generative-model", "inverse-design", "mlmd". This app belongs to WP11. Thanks, for all and let me know if there is something else to do.
> 
> Thanks a lot! Your app is now listed on the BIG-MAP App Store (https://big-map.github.io/big-map-registry/index.html).

Thanks a lot!

**Pull request merged**
