### PR TITLE
Add app <FullProfAPP-beta>

### PR DESCRIPTION
**Pull request by oarcelus**
This is a pull request to add the beta version deliverable of the FullProfAPP. (Stakeholder Initiatives)

### CODE REVIEW

**Comment by giovannipizzi** [comment]
Thanks for the contribution!
You mention:

> Any interested user is free to contact us through the following email (fullprofapp@cicenergigune.com) to gain access to the repository containing the beta version of FullProfAPP.

but we would like to host in this app store only apps that are open source or easily accessible.

Can you please clarify the difference between what could be obtained via email, and what is the content of the linked GitHub repository?

**Comment by oarcelus** [comment]
Hi Giovanni, sorry for the confusion. The repository containing the beta version of the app was made public right after I did the pull request. However, for the purposes of the project deliverable, and considering that the app is still in its beta version, we decided to distribute the executable binaries, so that testers try to find bugs in the program. Of course, the source code will be completely free for the final deliverable. But I can definitely share it with whoever is interested in inspecting it if they contact me.

I deleted the text section in the .yaml file.

**Comment by oarcelus** [comment]
I have just did the changes to the .yaml file. Will it be possible to redirect the link in the registry to another repository in the future? Once the full release is ready?

**Comment by csadorf** [comment]
> I have just made the changes to the .yaml file. Will it be possible to redirect the link in the registry to another repository in the future? Once the full release is ready?

Yes, we can update the link at any time, no problem.

**Review by csadorf — APPROVED** [review]

**Pull request merged**
